package gui;

import Modelo.ModeloAutores;
import Modelo.ModeloPais;
import Modelo.Modeloidioma;
import java.awt.HeadlessException;
import java.sql.Date;
import java.util.ArrayList;
import logico.Conexion;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import logico.Autor;
import logico.Idioma;
import logico.Pais;

/**
 *
 * @author Fiction
 */
public final class Ventana_Autor extends javax.swing.JDialog {

    /**
     * Creates new form Autor
     *
     * @param parent
     * @param modal
     */
    Conexion con = new Conexion();
    int ida;
    ModeloAutores ma = new ModeloAutores();

    public Ventana_Autor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarIdiomaAutor();
        llenarPaisAutor();
        //llenarComboAutor();
        ModeloAutores.getTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        backround = new javax.swing.JPanel();
        panelsuperior1 = new javax.swing.JPanel();
        labellog1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaautores = new javax.swing.JTable();
        labelced = new javax.swing.JLabel();
        txtcodigoautor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        labelnomprimero = new javax.swing.JLabel();
        txtnombreprimero = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        labelapesegundo = new javax.swing.JLabel();
        txtapellidosegundo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        labelpais = new javax.swing.JLabel();
        combopaisorigen = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JPanel();
        btnlabelLimpar = new javax.swing.JLabel();
        btnragregar = new javax.swing.JPanel();
        btnlabelagregar = new javax.swing.JLabel();
        btnactualizar = new javax.swing.JPanel();
        btnlabelactualizar = new javax.swing.JLabel();
        btneliminar = new javax.swing.JPanel();
        btnlabeleliminar = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JPanel();
        btnlabelbuscar = new javax.swing.JLabel();
        btnrvolver = new javax.swing.JPanel();
        btnlabelvolver = new javax.swing.JLabel();
        labelnomsegundo = new javax.swing.JLabel();
        txtnombresegundo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        labelape1 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        labelid = new javax.swing.JLabel();
        campoid = new javax.swing.JLabel();
        fecha_nac_chooser = new com.toedter.calendar.JDateChooser();
        labelfecha = new javax.swing.JLabel();
        combolengua = new javax.swing.JComboBox<>();
        labelfecha1 = new javax.swing.JLabel();
        checkFiltro = new javax.swing.JCheckBox();
        checkCancellDelete = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backround.setBackground(new java.awt.Color(255, 255, 255));

        panelsuperior1.setBackground(new java.awt.Color(0, 153, 153));

        labellog1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labellog1.setForeground(new java.awt.Color(255, 255, 255));
        labellog1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labellog1.setText("REGISTRAR AUTORES");

        javax.swing.GroupLayout panelsuperior1Layout = new javax.swing.GroupLayout(panelsuperior1);
        panelsuperior1.setLayout(panelsuperior1Layout);
        panelsuperior1Layout.setHorizontalGroup(
            panelsuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsuperior1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labellog1)
                .addContainerGap(635, Short.MAX_VALUE))
        );
        panelsuperior1Layout.setVerticalGroup(
            panelsuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsuperior1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(labellog1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tablaautores = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tablaautores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_aut", "nombre_aut", "apellido_aut ", "pais_origen_aut"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaautores.setFocusable(false);
        tablaautores.getTableHeader().setReorderingAllowed(false);
        tablaautores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaautoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaautores);

        labelced.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        labelced.setForeground(new java.awt.Color(102, 102, 102));
        labelced.setText("CÓDIGO:");

        txtcodigoautor.setBorder(null);
        txtcodigoautor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoautorKeyTyped(evt);
            }
        });

        labelnomprimero.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        labelnomprimero.setForeground(new java.awt.Color(102, 102, 102));
        labelnomprimero.setText("PRIMER NOMBRE:");

        txtnombreprimero.setBorder(null);
        txtnombreprimero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreprimeroKeyTyped(evt);
            }
        });

        labelapesegundo.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        labelapesegundo.setForeground(new java.awt.Color(102, 102, 102));
        labelapesegundo.setText("SEGUNDO APELLIDO:");

        txtapellidosegundo.setBorder(null);
        txtapellidosegundo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosegundoKeyTyped(evt);
            }
        });

        labelpais.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        labelpais.setForeground(new java.awt.Color(102, 102, 102));
        labelpais.setText("PAÍS DE ORIGEN:");

        combopaisorigen.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

        btnLimpiar.setBackground(new java.awt.Color(0, 153, 153));

        btnlabelLimpar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnlabelLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnlabelLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlabelLimpar.setText("LIMPIAR");
        btnlabelLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlabelLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlabelLimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlabelLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlabelLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        btnragregar.setBackground(new java.awt.Color(0, 153, 153));

        btnlabelagregar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnlabelagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnlabelagregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlabelagregar.setText("AGREGAR");
        btnlabelagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlabelagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlabelagregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnragregarLayout = new javax.swing.GroupLayout(btnragregar);
        btnragregar.setLayout(btnragregarLayout);
        btnragregarLayout.setHorizontalGroup(
            btnragregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlabelagregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnragregarLayout.setVerticalGroup(
            btnragregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlabelagregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        btnactualizar.setBackground(new java.awt.Color(0, 153, 153));

        btnlabelactualizar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnlabelactualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnlabelactualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlabelactualizar.setText("ACTUALIZAR");
        btnlabelactualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlabelactualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlabelactualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnactualizarLayout = new javax.swing.GroupLayout(btnactualizar);
        btnactualizar.setLayout(btnactualizarLayout);
        btnactualizarLayout.setHorizontalGroup(
            btnactualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlabelactualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnactualizarLayout.setVerticalGroup(
            btnactualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlabelactualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        btneliminar.setBackground(new java.awt.Color(0, 153, 153));

        btnlabeleliminar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnlabeleliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnlabeleliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlabeleliminar.setText("ELIMINAR");
        btnlabeleliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlabeleliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlabeleliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btneliminarLayout = new javax.swing.GroupLayout(btneliminar);
        btneliminar.setLayout(btneliminarLayout);
        btneliminarLayout.setHorizontalGroup(
            btneliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlabeleliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btneliminarLayout.setVerticalGroup(
            btneliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlabeleliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        btnbuscar.setBackground(new java.awt.Color(0, 153, 153));

        btnlabelbuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnlabelbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnlabelbuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlabelbuscar.setText("BUSCAR");
        btnlabelbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlabelbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlabelbuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnbuscarLayout = new javax.swing.GroupLayout(btnbuscar);
        btnbuscar.setLayout(btnbuscarLayout);
        btnbuscarLayout.setHorizontalGroup(
            btnbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlabelbuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnbuscarLayout.setVerticalGroup(
            btnbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlabelbuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        btnrvolver.setBackground(new java.awt.Color(0, 153, 153));

        btnlabelvolver.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnlabelvolver.setForeground(new java.awt.Color(255, 255, 255));
        btnlabelvolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlabelvolver.setText("VOLVER");
        btnlabelvolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlabelvolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlabelvolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnrvolverLayout = new javax.swing.GroupLayout(btnrvolver);
        btnrvolver.setLayout(btnrvolverLayout);
        btnrvolverLayout.setHorizontalGroup(
            btnrvolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlabelvolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnrvolverLayout.setVerticalGroup(
            btnrvolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlabelvolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        labelnomsegundo.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        labelnomsegundo.setForeground(new java.awt.Color(102, 102, 102));
        labelnomsegundo.setText("SEGUNDO NOMBRE:");

        txtnombresegundo.setBorder(null);
        txtnombresegundo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresegundoKeyTyped(evt);
            }
        });

        labelape1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        labelape1.setForeground(new java.awt.Color(102, 102, 102));
        labelape1.setText("PRIMER APELLIDO:");

        txtapellido.setBorder(null);
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });

        labelid.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        labelid.setForeground(new java.awt.Color(102, 102, 102));
        labelid.setText("ID:");

        campoid.setEnabled(false);

        fecha_nac_chooser.setDateFormatString("yyyy-MM-dd");

        labelfecha.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        labelfecha.setForeground(new java.awt.Color(102, 102, 102));
        labelfecha.setText("LENGUA MATERNA:");

        combolengua.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

        labelfecha1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        labelfecha1.setForeground(new java.awt.Color(102, 102, 102));
        labelfecha1.setText("FECHA NACIMIENTO:");

        checkFiltro.setText("FILTRAR ELIMINADOS");
        checkFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkFiltroMouseClicked(evt);
            }
        });

        checkCancellDelete.setText("CANCELAR ELIMINACION");
        checkCancellDelete.setEnabled(false);

        javax.swing.GroupLayout backroundLayout = new javax.swing.GroupLayout(backround);
        backround.setLayout(backroundLayout);
        backroundLayout.setHorizontalGroup(
            backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelsuperior1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backroundLayout.createSequentialGroup()
                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(backroundLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backroundLayout.createSequentialGroup()
                                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backroundLayout.createSequentialGroup()
                                        .addComponent(labelapesegundo)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backroundLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(labelpais, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backroundLayout.createSequentialGroup()
                                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(backroundLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(labelfecha1))
                                            .addComponent(labelfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(txtapellidosegundo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(combopaisorigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fecha_nac_chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combolengua, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backroundLayout.createSequentialGroup()
                                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelnomprimero, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelnomsegundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelape1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnombreprimero, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombresegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(backroundLayout.createSequentialGroup()
                                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelced, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelid, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcodigoautor)
                                    .addComponent(campoid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(checkCancellDelete))
                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backroundLayout.createSequentialGroup()
                                .addGap(582, 582, 582)
                                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnbuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnragregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnrvolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkFiltro)
                                .addGap(239, 239, 239)))))
                .addGap(24, 24, 24))
        );
        backroundLayout.setVerticalGroup(
            backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backroundLayout.createSequentialGroup()
                .addComponent(panelsuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backroundLayout.createSequentialGroup()
                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoid, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcodigoautor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelced, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnombreprimero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelnomprimero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnombresegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelnomsegundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelape1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtapellidosegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelapesegundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combolengua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backroundLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(labelfecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(backroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fecha_nac_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelpais, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(combopaisorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(checkCancellDelete)
                        .addGap(8, 8, 8))
                    .addGroup(backroundLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(backroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnragregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkFiltro))
                        .addGap(12, 12, 12)
                        .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnrvolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jScrollPane2.setViewportView(backround);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void llenarComboAutor(){
        
        Modeloidioma modidioma = new Modeloidioma();
        ArrayList<Idioma> listaIdiomas = modidioma.getIdioma();
        combolengua.removeAllItems();
        for (int i = 0; i < listaIdiomas.size(); i++) {
            combolengua.addItem(new Idioma(listaIdiomas.get(i).getId_idioma(), listaIdiomas.get(i).getNombre_idioma(), listaIdiomas.get(i).getDescripcion()));
        }
        
//        ModeloPais modpa = new ModeloPais();
//        ArrayList<Pais> listaPaises = modpa.getPais();
//        combolengua.removeAllItems();
//        for (int i = 0; i < listaPaises.size(); i++) {
//            combopaisorigen.addItem(new Pais(listaPaises.get(i).getNombre_pais()));
//        }
        
    }
    
    public void llenarIdiomaAutor() {
        Modeloidioma modidioma = new Modeloidioma();
        ArrayList<Idioma> listaIdiomas = modidioma.getIdioma();
        combolengua.removeAllItems();
        for (int i = 0; i < listaIdiomas.size(); i++) {
            combolengua.addItem(new Idioma(listaIdiomas.get(i).getId_idioma(), listaIdiomas.get(i).getNombre_idioma(), listaIdiomas.get(i).getDescripcion()));
        }
    }
    
    public void llenarPaisAutor() {
        ModeloPais modpa = new ModeloPais();
        ArrayList<Pais> listaPaises = modpa.getPais();
        combolengua.removeAllItems();
        for (int i = 0; i < listaPaises.size(); i++) {
            combopaisorigen.addItem(new Pais(listaPaises.get(i).getNombre_pais()));
        }
    }
    
    public void enableCheck(){
        checkCancellDelete.setEnabled(false);
        
        try{
            ModeloAutores mas = new ModeloAutores();
            int id = Integer.parseInt(campoid.getText());
            ArrayList<Autor> listaAutores = mas.getAutorEliminado();

            for(int i = 0; i < listaAutores.size(); i++){
                if(id == listaAutores.get(i).getId_autor()){
                    checkCancellDelete.setEnabled(true);
                    i = listaAutores.size();
                }
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "SELECCIONE UNA FILA DE LA TABLA");
        }
    }

    public void Registro() {
        try {
            Autor autor = new Autor();
            String codigo = txtcodigoautor.getText().trim();
            String nombre = txtnombreprimero.getText().trim();
            String nombre_s = txtnombresegundo.getText().trim();
            String apellido = txtapellido.getText().trim();
            String apellido_s = txtapellidosegundo.getText().trim();
            String lengua_mat = combolengua.getSelectedItem().toString();
            String fecha_nac = ((JTextField) fecha_nac_chooser.getDateEditor().getUiComponent()).getText();
            String pais_origen = combopaisorigen.getSelectedItem().toString();

            if (codigo.isEmpty() || nombre.isEmpty() || nombre_s.isEmpty() || apellido.isEmpty()
                    || apellido_s.isEmpty() || fecha_nac.isEmpty()) {
                JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
            } else {
                if (pais_origen.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "SELECCIONE UN PAÍS");
                } else {
                    if (lengua_mat.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "SELECCIONE UN IDIOMA");
                    } else {
                        if (autor.ValidarNombreYapellido(nombre) == false) {
                            JOptionPane.showMessageDialog(null, "PRIMER NOMBRE NO VÁLIDO");
                        } else {
                            if (autor.ValidarNombreYapellido(nombre_s) == false) {
                                JOptionPane.showMessageDialog(null, "SEGUNDO NOMBRE NO VÁLIDO");
                            } else {
                                if (autor.ValidarNombreYapellido(apellido) == false) {
                                    JOptionPane.showMessageDialog(null, "PRIMER APELLIDO NO VÁLIDO");
                                } else {
                                    if (autor.ValidarNombreYapellido(apellido_s) == false) {
                                        JOptionPane.showMessageDialog(null, "SEGUNDO APELLIDO NO VÁLIDO");
                                    } else {
                                        autor.setCedula(codigo);
                                        autor.setPrimer_nombre(nombre);
                                        autor.setPrimer_nombre(nombre_s);
                                        autor.setPrimer_apellido(apellido);
                                        autor.setSegundo_nombre(nombre_s);
                                        autor.setSegundo_apellido(apellido_s);
                                        autor.setFecha_nac(Date.valueOf(fecha_nac));
                                        autor.setLengua_materna(lengua_mat);
                                        autor.setPais_origen(pais_origen);
                                        if (ma.RegistrarAutor(autor)) {
                                            JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO");
                                            ModeloAutores.Limpiar_Tabla();
                                            ModeloAutores.getTabla();
                                            LimpiarCampos();
                                        } else {
                                            JOptionPane.showMessageDialog(null, "NO SE PUDO REGISTRAR EL AUTOR");
                                            ModeloAutores.Limpiar_Tabla();
                                            ModeloAutores.getTabla();
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } catch (HeadlessException | IllegalArgumentException e) {
            System.out.println(e);
        }
//    
//    public void consultar_Parametro(){
//        try{
//            String id = JOptionPane.showInputDialog(null, "INGRESE EL EL PAÍS DE ORIGEN");
////            int id_ = Integer.parseInt(id);
//            
//            String sql = "SELECT * FROM AUTOR WHERE pais_origen_aut=\""+id+"\"";
//            try {
//                con1 = con.getConnection(); 
//                st = con1.createStatement();
//                rs = st.executeQuery(sql);
//                Limpiar_Tabla();
//                Object [] Autor = new Object[4];
//                model = (DefaultTableModel) tablaautores.getModel();
//
//                while (rs.next()) {                
//                    Autor [0] = rs.getInt("id_aut");
//                    Autor [1] = rs.getString("nombre_aut");
//                    Autor [2] = rs.getString("apellido_aut");
//                    Autor [3] = rs.getString("pais_origen_aut");
//                    model.addRow(Autor);
//                    tablaautores.setModel(model);
//                }
//            } catch (SQLException e) { 
//            }
//        }catch(HeadlessException | NumberFormatException e){
//            JOptionPane.showMessageDialog(null, "NO SE PUDO HACER LA BÚSQUEDA");
//        }
    }

    public void Modificar(){
        try{
            Autor autor = new Autor();
            int id = Integer.parseInt(campoid.getText().trim());
            String codigo = txtcodigoautor.getText().trim();
            String primer_nombre = txtnombreprimero.getText().trim();
            String primer_apellido = txtapellido.getText().trim();
            String segundo_nombre = txtnombresegundo.getText().trim();
            String segundo_apellido = txtapellidosegundo.getText().trim();
            String fecha_nac = ((JTextField) fecha_nac_chooser.getDateEditor().getUiComponent()).getText();
            String pais_origen = combopaisorigen.getSelectedItem().toString();
            String lengua = combolengua.getSelectedItem().toString();

            try {
                if(primer_nombre.isEmpty() || primer_apellido.isEmpty() || segundo_nombre.isEmpty() || segundo_apellido.isEmpty() || fecha_nac.isEmpty()
                        || combopaisorigen.getSelectedItem().toString().equalsIgnoreCase("SELECCIONAR")){
                    JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
                    LimpiarCampos();
                } else{
                    if(!autor.ValidarCedula(codigo) || !autor.ValidarNombresYapellidos(primer_nombre) || !autor.ValidarNombresYapellidos(primer_apellido) || !autor.ValidarNombresYapellidos(segundo_nombre) || !autor.ValidarNombresYapellidos(segundo_apellido)){
                        JOptionPane.showMessageDialog(null, "VERIFIQUE LOS CAMPOS");
                        LimpiarCampos();
                    }else{
                        autor.setId_autor(id);
                        autor.setCedula(codigo);
                        autor.setPrimer_nombre(primer_nombre);
                        autor.setSegundo_nombre(segundo_nombre);
                        autor.setPrimer_apellido(primer_apellido);
                        autor.setSegundo_apellido(segundo_apellido);
                        autor.setFecha_nac(Date.valueOf(fecha_nac));
                        autor.setPais_origen(pais_origen);
                        autor.setLengua_materna(lengua);
                        if(ma.ModificarAutor(autor)){
                            JOptionPane.showMessageDialog(null, "AUTOR ACTUALIZADO CORRECTAMENTE");
                            ModeloAutores.getTabla();
                            LimpiarCampos();
                        }else{
                            JOptionPane.showMessageDialog(null, "NO SE PUDO ACTUALIZAR");
                        }
                    }
                }
           } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, "ERROR-NO SE PUDO MODIFICAR AL AUTOR");
            }
        }catch(HeadlessException | NumberFormatException e){
            System.out.println(e);
        }
    }
    
    public void ModificarEliminado(){
        try{
            Autor autor = new Autor();
            int id = Integer.parseInt(campoid.getText().trim());
            String codigo = txtcodigoautor.getText().trim();
            String primer_nombre = txtnombreprimero.getText().trim();
            String primer_apellido = txtapellido.getText().trim();
            String segundo_nombre = txtnombresegundo.getText().trim();
            String segundo_apellido = txtapellidosegundo.getText().trim();
            String fecha_nac = ((JTextField) fecha_nac_chooser.getDateEditor().getUiComponent()).getText();
            String pais_origen = combopaisorigen.getSelectedItem().toString();
            String lengua = combolengua.getSelectedItem().toString();
            boolean bo1;
            bo1 = !checkCancellDelete.isSelected();

            try {
                if(primer_nombre.isEmpty() || primer_apellido.isEmpty() || segundo_nombre.isEmpty() || segundo_apellido.isEmpty() || fecha_nac.isEmpty()
                        || combopaisorigen.getSelectedItem().toString().equalsIgnoreCase("SELECCIONAR")){
                    JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
                } else{
                    if(!autor.ValidarCedula(codigo) || !autor.ValidarNombresYapellidos(primer_nombre) || !autor.ValidarNombresYapellidos(primer_apellido) || !autor.ValidarNombresYapellidos(segundo_nombre) || !autor.ValidarNombresYapellidos(segundo_apellido)){
                        JOptionPane.showMessageDialog(null, "VERIFIQUE LOS CAMPOS");
                    }else{
                        autor.setId_autor(id);
                        autor.setCedula(codigo);
                        autor.setPrimer_nombre(primer_nombre);
                        autor.setPrimer_apellido(primer_apellido);
                        autor.setSegundo_nombre(segundo_nombre);
                        autor.setSegundo_apellido(segundo_apellido);
                        autor.setFecha_nac(Date.valueOf(fecha_nac));
                        autor.setPais_origen(pais_origen);
                        autor.setLengua_materna(lengua);
                        autor.setEstado(bo1);
                        if(ma.ModificarAutorEliminado(autor)){
                            JOptionPane.showMessageDialog(null, "AUTOR ACTUALIZADO CORRECTAMENTE");
                            ModeloAutores.getTablaEliminados();
                            //LimpiarCampos();
                        }else{
                            JOptionPane.showMessageDialog(null, "NO SE PUDO ACTUALIZAR");
                        }
                    }
                }
           } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, "ERROR-NO SE PUDO MODIFICAR AL AUTOR");
            }
        }catch(HeadlessException | NumberFormatException | NullPointerException e){
            JOptionPane.showMessageDialog(null, "ELIJA UNA FILA DE LA TABLA");
        }
    }
    
    public void Eliminar() {
        try {
            Autor autor = new Autor();
            int fila = Integer.parseInt(campoid.getText().trim());

            autor.setId(fila);
            if (ma.EliminarAutor(autor)) {
                JOptionPane.showMessageDialog(null, "AUTOR ELIMINADO CON ÉXITO");
                ModeloAutores.getTabla();
            }else{
                JOptionPane.showMessageDialog(null, "NO SE PUDO ELIMINAR EL AUTOR");
                ModeloAutores.getTabla();
            }
        }catch(HeadlessException | NumberFormatException | NullPointerException e){
            System.out.println(e);
        }
    }
    
    public void LimpiarCampos() {
        campoid.setText(null);
        txtcodigoautor.setText(null);
        txtnombreprimero.setText(null);
        txtnombresegundo.setText(null);
        txtapellido.setText(null);
        txtapellidosegundo.setText(null);
        combolengua.setSelectedIndex(0);
        fecha_nac_chooser.setCalendar(null);
        combopaisorigen.setSelectedIndex(0);
        checkCancellDelete.setSelected(false);
    }

    private void txtcodigoautorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoautorKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            if (txtcodigoautor.getText().length() >= 10) {
                evt.consume();
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtcodigoautorKeyTyped

    private void txtnombreprimeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreprimeroKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            evt.consume();
        } else {
            if (txtnombreprimero.getText().length() >= 50) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtnombreprimeroKeyTyped

    private void txtapellidosegundoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosegundoKeyTyped
        if (txtapellidosegundo.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtapellidosegundoKeyTyped

    private void btnlabelLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlabelLimparMouseClicked
        LimpiarCampos();
        ModeloAutores.Limpiar_Tabla();
        ModeloAutores.getTabla();
    }//GEN-LAST:event_btnlabelLimparMouseClicked

    private void btnlabelagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlabelagregarMouseClicked
        Registro();
    }//GEN-LAST:event_btnlabelagregarMouseClicked

    private void btnlabelactualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlabelactualizarMouseClicked
        if(checkCancellDelete.isEnabled()){
            ModificarEliminado();
            LimpiarCampos();
        }else{
            Modificar();
            LimpiarCampos();
        }
    }//GEN-LAST:event_btnlabelactualizarMouseClicked

    private void btnlabeleliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlabeleliminarMouseClicked
        if(!checkFiltro.isSelected()){
            Eliminar();
            LimpiarCampos();
        }else{
            JOptionPane.showMessageDialog(null, "NO SE PUEDE ELIMINAR ESTANDO ACTIVO EL FILTRO DE ELIMINADOS");
        }
    }//GEN-LAST:event_btnlabeleliminarMouseClicked

    private void btnlabelbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlabelbuscarMouseClicked
        //consultar_Parametro();
    }//GEN-LAST:event_btnlabelbuscarMouseClicked

    private void tablaautoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaautoresMouseClicked
        int fila = tablaautores.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "NO HAY UNA FILA SELECCIONADA");
        } else {
            campoid.disable();
            checkCancellDelete.setEnabled(false);
            ida = Integer.parseInt((String) tablaautores.getValueAt(fila, 0).toString());
            String codigo = (String) tablaautores.getValueAt(fila, 1);
            String nombre = (String) tablaautores.getValueAt(fila, 2);
            String segundo_nombre = (String) tablaautores.getValueAt(fila, 3);
            String apellido = (String) tablaautores.getValueAt(fila, 4);
            String segundo_apellido = (String) tablaautores.getValueAt(fila, 5);
            String lengua_materna = (String) tablaautores.getValueAt(fila, 6).toString();
            Date fecha_p = Date.valueOf((String) tablaautores.getValueAt(fila, 6).toString());
            String pais_origen = (String) tablaautores.getValueAt(fila, 8).toString();

            campoid.setText("" + ida);
            txtcodigoautor.setText(codigo);
            txtnombreprimero.setText(nombre);
            txtnombresegundo.setText(segundo_nombre);
            txtapellido.setText(apellido);
            txtapellidosegundo.setText(segundo_apellido);
            combolengua.setSelectedItem(lengua_materna);
            fecha_nac_chooser.setDate(fecha_p);
            combopaisorigen.setSelectedItem(pais_origen);
            enableCheck();
        }
    }//GEN-LAST:event_tablaautoresMouseClicked

    private void btnlabelvolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlabelvolverMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnlabelvolverMouseClicked

    private void txtnombresegundoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresegundoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombresegundoKeyTyped

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void checkFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkFiltroMouseClicked
        if(checkFiltro.isSelected()){
            ModeloAutores.getTablaEliminados();
        }else{
            ModeloAutores.getTabla();
            checkCancellDelete.setEnabled(false);
        }
    }//GEN-LAST:event_checkFiltroMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backround;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnactualizar;
    private javax.swing.JPanel btnbuscar;
    private javax.swing.JPanel btneliminar;
    private javax.swing.JLabel btnlabelLimpar;
    private javax.swing.JLabel btnlabelactualizar;
    private javax.swing.JLabel btnlabelagregar;
    private javax.swing.JLabel btnlabelbuscar;
    private javax.swing.JLabel btnlabeleliminar;
    private javax.swing.JLabel btnlabelvolver;
    private javax.swing.JPanel btnragregar;
    private javax.swing.JPanel btnrvolver;
    private javax.swing.JLabel campoid;
    private javax.swing.JCheckBox checkCancellDelete;
    private javax.swing.JCheckBox checkFiltro;
    private javax.swing.JComboBox<Idioma> combolengua;
    private javax.swing.JComboBox<Pais> combopaisorigen;
    private com.toedter.calendar.JDateChooser fecha_nac_chooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelape1;
    private javax.swing.JLabel labelapesegundo;
    private javax.swing.JLabel labelced;
    private javax.swing.JLabel labelfecha;
    private javax.swing.JLabel labelfecha1;
    private javax.swing.JLabel labelid;
    private javax.swing.JLabel labellog1;
    private javax.swing.JLabel labelnomprimero;
    private javax.swing.JLabel labelnomsegundo;
    private javax.swing.JLabel labelpais;
    private javax.swing.JPanel panelsuperior1;
    public static javax.swing.JTable tablaautores;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtapellidosegundo;
    private javax.swing.JTextField txtcodigoautor;
    private javax.swing.JTextField txtnombreprimero;
    private javax.swing.JTextField txtnombresegundo;
    // End of variables declaration//GEN-END:variables
}
